# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163dce847fccb34a7b009c4c80cc087a1051c8e28075d1c98b76ee4af10c5cee60f7d4f077fc0a0a69cf92692eb7d1d3a4219352ff41ab25b2a90e1f9936e978

test:
  secret_key_base: 4f81b64dc6ad11a3a192a4a7c42efe5352d11a9495c18dd356d4b22d8e893ab2071c557e8ec7179d6723c1b6a1d490c1d30bcf2b5477d7251f1075a60bb1cda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
